body:
  application/json:
    example: |
      {
        "data": [],
        "meta": {
          "messages": [
            {
              "value": "A message, like invalid field etc.",
              "type": "error"
            }
          ]
        }
      }
