body:
  application/json:
    example: |
      "data": {
        "context": "Woensdag bugfixdag",
        "datetime": "2007-04-17 17:31:36",
        "id": "252",
        "kudos": null,
        "person": "Jan Jansen",
        "quote": "Ja sorry, ik ben standaard elke woensdag ziek",
        "user": "1"
      },
      "meta": []
