200:
  body:
    application/json:
      example: |
        {
          "data": {
            "email": "email@email.com"
            "id": 434,
            "name": "full name",
            "username": "username"
          },
          "meta": []
        }
400: !include ../generic/response_error.raml