description: Collection of quotes.
get:
  description: Get a list of quotes based on filter parameters.
  queryParameters:
    random:
      description: "Get random quotes, returns 5 random quotes."
      required: false
      type: string
      example: "?random=1"
  responses:
    200: !include quotes/response200.raml
post:
  description: Create a quote.
  body:
    application/json:
      example: |
        {
          "context": "Woensdag bugfixdag",
          "datetime": "2007-04-17 17:31:36",
          "kudos": null,
          "person": "Jan Jansen",
          "quote": "Ja sorry, ik ben standaard elke woensdag ziek",
          "user": "1"
        }
  responses:
    200: !include quotes/response200.raml
    400:
      body:
        application/json:
          example: |
            "data": [],
            "meta": {
              "messages": [
                {
                  "value": "A message, like invalid field etc.",
                  "type": "error"
                }
              ]
            }
