description: Collection of quotes.
get:
  description: Get a list of quotes based on filter parameters.
  headers:
    X-Access-Token: !include generic/header_jwt_token.raml
  queryParameters:
    random:
      description: "Get random quotes, returns 5 random quotes."
      required: false
      type: string
      example: "?random=1"
  responses:
    200: !include quotes/response_200.raml
    403: !include generic/response_empty.raml
post:
  description: Create a quote.
  headers:
    X-Access-Token: !include generic/header_jwt_token.raml
  body:
    application/json:
      example: |
        {
          "context": "Woensdag bugfixdag",
          "datetime": "2007-04-17 17:31:36",
          "kudos": null,
          "person": "Jan Jansen",
          "quote": "Ja sorry, ik ben standaard elke woensdag ziek",
          "user": "1"
        }
  responses:
    200: !include quotes/response_200.raml
    400: !include generic/response_error.raml
    403: !include generic/response_empty.raml
/{quoteId}:
  delete:
    description: Delete a quote.
    headers:
      X-Access-Token: !include generic/header_jwt_token.raml
    responses:
      204:
        body:
          application/json: !!null
      403: !include generic/response_empty.raml
      404: !include generic/response_empty.raml
